server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spotifydata
    username: root
    password: ${SPOTIFY_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
  main:
    web-application-type: servlet